function( make_runtime_name variant name )
  if( CMAKE_SYSTEM_NAME MATCHES Windows)
    set(prefix "lib")
  else()
    set(prefix "")
  endif()
  if( CMAKE_SIZEOF_VOID_P EQUAL 8 )
    set( ${name} ${prefix}mfx${variant}64 PARENT_SCOPE)
  else()
    set( ${name} ${prefix}mfx${variant}32 PARENT_SCOPE)
  endif()
endfunction()

if( CMAKE_SYSTEM_NAME MATCHES Windows )
  message ( "Loading default win_x64 profile on Windows" )
  include ( ${BUILDER_ROOT}/profiles/win_x64.cmake )
endif()