####################################################################################
#
# INTEL CORPORATION PROPRIETARY INFORMATION
# This software is supplied under the terms of a license agreement or nondisclosure
# agreement with Intel Corporation and may not be copied or disclosed except in
# accordance with the terms of that agreement
# Copyright(c) 2010-2012 Intel Corporation. All Rights Reserved.
#
####################################################################################

# Importing python-wide modules
import os
import sys

# Setting additional search paths for MFX custom python scripts (modules)
sys.path.append(os.path.abspath('..' + os.sep + 'scons' + os.sep + '_mfx'))

# Importing MFX custom modules
import mfx_init as mfx
import mfx_utils
import mfx_common
import mfx_ipp

# Importing variables
Import('mfx_src_root')
Import('mfx_root_env')

# Setting some variables
cur_dir = mfx_utils.get_related_path(mfx_src_root, '.')

# Setting subdirectories to march thru
dirs = ['dxva2_dump'
        ,'shared'
        ,'mfx_player'
        ,'mfx_transcoder'
        ,'calc_crc'
        ,'interlace_maker'
        ,'convertnv12'
        ,'test_vpp'
#        ,'metrics_calc_lite'
        ,'tools'
        ,'ldecod'
        ,'ref_frc'
        ,'detail_enh'
        ,'tc'
        ,'proc_amp'
        ,'ldecodqp'
        ,'ldecodrpl'
        ,'stream_maker'
        ,'convertyuy2'
        ,'test_thread_safety'
        ,'i965_hook'
#        ,'rtest'
        ,'libva_hook'
        ,'bs_parser'
        ,'streams_generator'
        ,'behavior'
        ,'csc_tool'
        ,'ref_ltbx'
        ,'test_session_priority'
        ,'os'
        ,'cocoto'
        ,'msdk_ts'
        ]

# Creating environment to build projects in this directory
mfx_tst_env = mfx_root_env.Clone()

if mfx_common.set_mfx_env_common(mfx_tst_env) or mfx_ipp.set_mfx_env_ipp(mfx_tst_env, ARGUMENTS):
  print "MFX BUILD ERROR: can't build targets in directory %s!" % cur_dir
else:
  mfx_tst_lib_env = mfx_tst_env.Clone()
  mfx.set_static_env(mfx_tst_lib_env)
  # Exporing variables
  Export('mfx_tst_env')
  Export('mfx_tst_lib_env')
  # Marching thru subdirectories
  mfx_utils.run_subdirs(dirs, 'SConscript')
