####################################################################################
#
# INTEL CORPORATION PROPRIETARY INFORMATION
# This software is supplied under the terms of a license agreement or nondisclosure
# agreement with Intel Corporation and may not be copied or disclosed except in
# accordance with the terms of that agreement
# Copyright(c) 2010-2011 Intel Corporation. All Rights Reserved.
#
####################################################################################

# Importing python-wide modules
import os

# Importing MFX utilities module
import mfx_utils

# Importing variables
Import('mfx_src_root')
Import('mfx_bld_root')
Import('mfx_lib_env')

bld_env = mfx_lib_env.Clone()

# Setting build dir
cur_dir = mfx_utils.get_related_path(mfx_src_root, '.')
bld_dir = mfx_bld_root + os.sep + cur_dir

# Setting subdirectories to march thru
dirs = ['asf_spl',
        'avi_spl',
        'brc',
        'common',
        'demuxer',
        'h264_enc',
        'h264_spl',
        'mpeg2_enc',
        'mpeg4_spl',
        'scene_analyzer',
        'spl_common',
        'vc1_common',
        'vc1_enc',
        'vc1_spl',
        'jpeg_common',
        'jpeg_enc']

dirs_impl = ['color_space_converter',
             'jpeg_dec',
             'mpeg2_dec',
             'vc1_dec',
             'h264_dec'
            ]

# Marching thru subdirectories
nodes = mfx_utils.run_subdirs(dirs, 'SConscript')
nodes_impl = mfx_utils.run_subdirs(dirs_impl, 'SConscript')

# Creating list of objects to build merged library
umc_codec_merged_objs = list()
umc_codec_merged_impl_objs = list()
count = mfx_utils.exclude_empty_nodes(nodes, umc_codec_merged_objs)
count_impl = mfx_utils.exclude_empty_nodes(nodes_impl, umc_codec_merged_impl_objs)
if count != 0 or count_impl != 0:
  print 'MFX BUILD NOTE: empty nodes count is %d. Check your build!' % (count + count_impl)

# Building merged library
SConscript('SConscriptTarget_codecs', variant_dir = bld_dir, duplicate = 0, exports = 'umc_codec_merged_objs')
SConscript('SConscriptTarget_codecs_impl', variant_dir = bld_dir, duplicate = 0, exports = 'umc_codec_merged_impl_objs')
