####################################################################################
#
# INTEL CORPORATION PROPRIETARY INFORMATION
# This software is supplied under the terms of a license agreement or nondisclosure
# agreement with Intel Corporation and may not be copied or disclosed except in
# accordance with the terms of that agreement
# Copyright(c) 2010 Intel Corporation. All Rights Reserved.
#
####################################################################################

# Importing python-wide modules
import os

# Importing MFX utilities module
import mfx_utils

# Importing variables
Import('mfx_src_root')
Import('mfx_bld_root')

# Setting build dir
cur_dir = mfx_utils.get_related_path(mfx_src_root, '.')
bld_dir = mfx_bld_root + os.sep + cur_dir

# Building target(s)
nodes = list()
nodes.append(SConscript('SConscriptTarget__mfx_common', variant_dir = bld_dir, duplicate = 0))
nodes.append(SConscript('SConscriptTarget__mfx_common_hw', variant_dir = bld_dir, duplicate = 0))
nodes.append(SConscript('SConscriptTarget__vc1_shared', variant_dir = bld_dir, duplicate = 0))

Return('nodes')
