EXTBUF(mfxExtCodingOption           , MFX_EXTBUFF_CODING_OPTION             )
EXTBUF(mfxExtCodingOptionSPSPPS     , MFX_EXTBUFF_CODING_OPTION_SPSPPS      )
EXTBUF(mfxExtVPPDoNotUse            , MFX_EXTBUFF_VPP_DONOTUSE              )
EXTBUF(mfxExtVppAuxData             , MFX_EXTBUFF_VPP_AUXDATA               )
EXTBUF(mfxExtVPPDenoise             , MFX_EXTBUFF_VPP_DENOISE               )
EXTBUF(mfxExtVPPProcAmp             , MFX_EXTBUFF_VPP_PROCAMP               )
EXTBUF(mfxExtVPPDetail              , MFX_EXTBUFF_VPP_DETAIL                )
EXTBUF(mfxExtVideoSignalInfo        , MFX_EXTBUFF_VIDEO_SIGNAL_INFO         )
EXTBUF(mfxExtVPPDoUse               , MFX_EXTBUFF_VPP_DOUSE                 )
EXTBUF(mfxExtOpaqueSurfaceAlloc     , MFX_EXTBUFF_OPAQUE_SURFACE_ALLOCATION )
EXTBUF(mfxExtAVCRefListCtrl         , MFX_EXTBUFF_AVC_REFLIST_CTRL          )
EXTBUF(mfxExtVPPFrameRateConversion , MFX_EXTBUFF_VPP_FRAME_RATE_CONVERSION )
EXTBUF(mfxExtPictureTimingSEI       , MFX_EXTBUFF_PICTURE_TIMING_SEI        )
EXTBUF(mfxExtAvcTemporalLayers      , MFX_EXTBUFF_AVC_TEMPORAL_LAYERS       )
EXTBUF(mfxExtCodingOption2          , MFX_EXTBUFF_CODING_OPTION2            )
EXTBUF(mfxExtVPPImageStab           , MFX_EXTBUFF_VPP_IMAGE_STABILIZATION   )
EXTBUF(mfxExtEncoderCapability      , MFX_EXTBUFF_ENCODER_CAPABILITY        )
EXTBUF(mfxExtEncoderResetOption     , MFX_EXTBUFF_ENCODER_RESET_OPTION      )
EXTBUF(mfxExtAVCEncodedFrameInfo    , MFX_EXTBUFF_ENCODED_FRAME_INFO        )
EXTBUF(mfxExtVPPComposite           , MFX_EXTBUFF_VPP_COMPOSITE             )
EXTBUF(mfxExtVPPVideoSignalInfo     , MFX_EXTBUFF_VPP_VIDEO_SIGNAL_INFO     )
EXTBUF(mfxExtEncoderROI             , MFX_EXTBUFF_ENCODER_ROI               )
EXTBUF(mfxExtVPPDeinterlacing       , MFX_EXTBUFF_VPP_DEINTERLACING         )
EXTBUF(mfxExtCodingOptionVP8        , MFX_EXTBUFF_VP8_EX_CODING_OPT         )
//EXTBUF(mfxExtMVCSeqDesc             , MFX_EXTBUFF_MVC_SEQ_DESC              );
//EXTBUF(mfxExtMVCTargetViews         , MFX_EXTBUFF_MVC_TARGET_VIEWS          );
//EXTBUF(mfxExtJPEGQuantTables        , MFX_EXTBUFF_JPEG_QT                   );
//EXTBUF(mfxExtJPEGHuffmanTables      , MFX_EXTBUFF_JPEG_HUFFMAN              );
//EXTBUF(mfxExtPAVPOption             , MFX_EXTBUFF_PAVP_OPTION               );