@echo off
call build_kernel.cmd analyze_gradient hsw /Qxcm_release
call build_kernel.cmd analyze_gradient2 hsw /Qxcm_release
call build_kernel.cmd analyze_gradient3 hsw /Qxcm_release
call build_kernel.cmd analyze_gradient8x8 hsw /Qxcm_release
call build_kernel.cmd analyze_gradient_32x32_best hsw /Qxcm_release
call build_kernel.cmd analyze_gradient_32x32_modes hsw /Qxcm_release
call build_kernel.cmd deblock hsw /Qxcm_release
call build_kernel.cmd down_sample_mb hsw /Qxcm_release
call build_kernel.cmd down_sample_mb_2tiers hsw /Qxcm_release
call build_kernel.cmd down_sample_mb_4tiers hsw /Qxcm_release
call build_kernel.cmd ime_4mv hsw /Qxcm_release
call build_kernel.cmd ime_3tiers_4mv hsw /Qxcm_release
call build_kernel.cmd interpolate_frame hsw /Qxcm_release
call build_kernel.cmd intra_i16 hsw /Qxcm_release
call build_kernel.cmd me_p16_4mv hsw /Qxcm_release
call build_kernel.cmd me_p32_4mv hsw /Qxcm_release
call build_kernel.cmd refine_me_p_16x32 hsw /Qxcm_release
call build_kernel.cmd refine_me_p_32x16 hsw /Qxcm_release
call build_kernel.cmd refine_me_p_32x32 hsw /Qxcm_release
call build_kernel.cmd refine_me_p_16x32_sad hsw /Qxcm_release
call build_kernel.cmd refine_me_p_32x16_sad hsw /Qxcm_release
call build_kernel.cmd refine_me_p_32x32_sad hsw /Qxcm_release
call build_kernel.cmd refine_me_p_32x32_satd4x4 hsw /Qxcm_release
call build_kernel.cmd refine_me_p_32x32_satd8x8 hsw /Qxcm_release
call build_kernel.cmd refine_me_p_combine hsw /Qxcm_release
call build_kernel.cmd refine_me_p_satd4x4_combine hsw /Qxcm_release
call build_kernel.cmd refine_me_p_satd8x8_combine hsw /Qxcm_release

call build_kernel.cmd analyze_gradient bdw /Qxcm_release
call build_kernel.cmd analyze_gradient2 bdw /Qxcm_release
call build_kernel.cmd analyze_gradient3 bdw /Qxcm_release
call build_kernel.cmd analyze_gradient8x8 bdw /Qxcm_release
call build_kernel.cmd analyze_gradient_32x32_best bdw /Qxcm_release
call build_kernel.cmd analyze_gradient_32x32_modes bdw /Qxcm_release
call build_kernel.cmd deblock bdw /Qxcm_release
call build_kernel.cmd down_sample_mb bdw /Qxcm_release
call build_kernel.cmd down_sample_mb_2tiers bdw /Qxcm_release
call build_kernel.cmd down_sample_mb_4tiers bdw /Qxcm_release
call build_kernel.cmd ime_4mv bdw /Qxcm_release
call build_kernel.cmd ime_3tiers_4mv bdw /Qxcm_release
call build_kernel.cmd interpolate_frame bdw /Qxcm_release
call build_kernel.cmd intra_i16 bdw /Qxcm_release
call build_kernel.cmd me_p16_4mv bdw /Qxcm_release
call build_kernel.cmd me_p32_4mv bdw /Qxcm_release
call build_kernel.cmd refine_me_p_16x32 bdw /Qxcm_release
call build_kernel.cmd refine_me_p_32x16 bdw /Qxcm_release
call build_kernel.cmd refine_me_p_32x32 bdw /Qxcm_release
call build_kernel.cmd refine_me_p_16x32_sad bdw /Qxcm_release
call build_kernel.cmd refine_me_p_32x16_sad bdw /Qxcm_release
call build_kernel.cmd refine_me_p_32x32_sad bdw /Qxcm_release
call build_kernel.cmd refine_me_p_32x32_satd4x4 bdw /Qxcm_release
call build_kernel.cmd refine_me_p_32x32_satd8x8 bdw /Qxcm_release
call build_kernel.cmd refine_me_p_combine bdw /Qxcm_release
call build_kernel.cmd refine_me_p_satd4x4_combine bdw /Qxcm_release
call build_kernel.cmd refine_me_p_satd8x8_combine bdw /Qxcm_release
